### ISSUE TITLE
Completar y actualizar datos en tabla estudiantes

### ISSUE THREAD

**Issue by Claudiars20** [Claudiars20/PSG.Backend#2]
- [x] Crear excel bajo formato con datos reales

**Comment by Marko99-CC** [comment]
Se creo un documento en formato .csv (Excel) con los datos reales de los estudiantes como:

- Código
- Nombre
- Apellido Paterno
- Apellido Materno
- Email
- Nro. Celular
- Dirección
- Semestre

La lista de estudiantes se encuentra en este documento: [https://docs.google.com/spreadsheets/d/1KMUrzaYUvfoMwZhZ0teTrLTUaewWCVsF917_412RYlM/edit?usp=sharing](url)
